name: Deploy Production Environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
      - name: AWS Account
        run: aws sts get-caller-identity
      - name: Deploy Infrastructure
        working-directory: ./scripts
        run: ./deploy_infrastructure.sh
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_public_ec2_key: ${{ vars.PUBLIC_EC2_KEY }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_secret_key_base: ${{ secrets.PHX_SECRET_KEY_BASE }}
      - name: Get Terraform Outputs
        working-directory: ./infra
        id: tofu_output
        run: |
          echo "ECS_CLUSTER=$(tofu output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "ECS_SERVICE=$(tofu output -raw ecs_service_name)" >> $GITHUB_OUTPUT
          echo "SUBNET_IDS=$(tofu output -json private_subnet_ids | jq -r 'join(",")')" >> $GITHUB_OUTPUT
          echo "ECS_SECURITY_GROUP_ID=$(tofu output -raw ecs_security_group_id)" >> $GITHUB_OUTPUT
      - name: Run Migrations
        run: |
          aws ecs run-task \
            --cluster ${{ steps.tofu_output.outputs.ECS_CLUSTER }} \
            --task-definition migration-task \
            --network-configuration "awsvpcConfiguration={subnets=[${{ steps.tofu_output.outputs.SUBNET_IDS }}],securityGroups=[${{ steps.tofu_output.outputs.ECS_SECURITY_GROUP_ID }}]}" \
            --launch-type FARGATE \
            --started-by "GitHub Actions"
      - name: Update ECS Cluster
        run: |
          aws ecs update-service \
            --cluster ${{ steps.tofu_output.outputs.ECS_CLUSTER }} \
            --service ${{ steps.tofu_output.outputs.ECS_SERVICE }} \
            --force-new-deployment
