name: Deploy Production Environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
      - name: AWS Account
        run: aws sts get-caller-identity
      - name: Deploy
        working-directory: ./scripts
        run: ./deploy.sh
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_public_ec2_key: ${{ var.PUBLIC_EC2_KEY }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
